# fly.toml app configuration file generated for dfs-api on 2025-09-28T03:52:27-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dfs-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEBUG = 'false'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2

[[vm]]
  cpu_kind = 'performance'
  cpus = 4
  memory_mb = 8192

[[metrics]]
  port = 9091
  path = '/metrics'
