app = "dfs-api"
primary_region = "iad"  # US East - closest to your RDS

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Keep running for zero cold starts
  auto_start_machines = true
  min_machines_running = 2    # High availability

[env]
  DEBUG = "false"

[[vm]]
  cpu_kind = "performance"
  cpus = 4                    # High CPU for optimizer
  memory_gb = 4               # Sufficient memory

[metrics]
  port = 9091
  path = "/metrics"